name: Django CI/CD Simulation

on:
  push:
    branches: [ main, cd-simulation ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test --verbosity=2

  build:
    name: Build and save Docker image
    needs: test     # 👈 Solo se ejecuta si los tests pasan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t django_ci_cd_app:${{ github.sha }} .

      - name: Save Docker image as tar.gz
        run: |
          mkdir -p artifacts
          docker save django_ci_cd_app:${{ github.sha }} | gzip > artifacts/django_ci_cd_app_${{ github.sha }}.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: django_docker_image
          path: artifacts/django_ci_cd_app_${{ github.sha }}.tar.gz
